package com.adrianodigiovanni.dailywifi.attempt;

enum ActionProgress {
	ACTIVE_NETWORK_IS_WIFI, ACCOUNT_EXISTS, ACTIVE_NETWORK_IS_CAPTIVE_AND_LOGGED_OUT, ACTIVE_NETWORK_IS_NOT_COMPATIBLE, LOGGED_IN, ALREADY_LOGGED_IN, CREDENTIALS_ARE_NOT_VALID, LOGGED_OUT, ALREADY_LOGGED_OUT
}
